#!/usr/bin/env python3
import yaml
import json
import sys
import arguably
import os
import fnmatch

def find(pattern, path):
    result = []
    for root, dirs, files in os.walk(path):
        for name in files:
            if fnmatch.fnmatch(name, pattern):
                result.append(os.path.join(root, name))
    return result

def get_alltypes(tmf, openapispec):
    print("types for: tmf=" + tmf + " openapispec=" + openapispec)
   
    with open(openapispec, 'r') as file:
        spec = yaml.safe_load(file)

    schemas = spec['components']['schemas']

    alltypes = {}

    for name, content in schemas.items():

        # filter basic types
        if "Integer" in name or "Float" in name or "String" in name or "Map" in name:
            continue

        # filter technical types
        if "Error" in name or "Hub" in name or "JsonPatch" in name:
            continue

        # filter the unknown FVO / MVO
        if "_FVO" in name or "_MVO" in name:
            continue

        # filter Payload / Event
        if "Event" in name or "Payload" in name:
            continue

        # filter refs
        if "Ref" in name:
            continue
        
        alltypes[name] = content
    
    return alltypes

def types_json_stdout(tmf, openapispec):

    alltypes = get_alltypes(tmf, openapispec)

    json_out = open('output/' + tmf + '/types.json', 'w')
    json.dump(alltypes, json_out, indent=4)
    json.dump(alltypes, sys.stdout, indent=4)

@arguably.command
def listapis():
    """
    list all TMF API Spec Names based on the directories in output
    """
    subfolders = [ f.path for f in os.scandir('output/') if f.is_dir() ]
    subfolders.sort()
    for folder in subfolders:
        print(folder.replace('output/', ''))
    
@arguably.command
def exportschemas(apis):
    """
    this exports the schemas of one or may apis to a types.json file

    Args:
        apis: the apis to get the schemas from e.g. TMF620. Can also be a list e.g. TMF620,TMF633
    """
    
    api_names = apis.split(',')

    
    for api_name in api_names:
        print("export for: " + api_name)
        openapi = find("*oas.yaml", "output/" + api_name)
        types_json_stdout(api_name, openapi[0])

@arguably.command
def schemas(apis, schema=None):
    """
    this gets a schema for a certain API or a list of APIs

    Args:
        api: the api to get the types from e.g. TMF620 or TMF620,TMF633
        schemas: the schemas to output e.g. TaxItem or TaxItem,Money
    """
    api_names = apis.split(',')

    if schema is not None:
        schemas = set(schema.split(','))

    alltypes = {}
    for api_name in api_names:
        openapi = find("*oas.yaml", "output/" + api_name)
        spec = yaml.safe_load(openapi[0])
        api_types = get_alltypes(api_name, spec)  
        alltypes.update(api_types)
    
    if schema is None:
        for name in alltypes:  
            print(name)
    else:
        for name in alltypes:  
            if  name in schemas:
                print("\n\n" + name + ":")
                json.dump(alltypes[name], sys.stdout, indent=4)

if __name__ == "__main__":
    arguably.run()